# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20171111_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='totalSavings',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Savings'),
        ),
    ]
