# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_users_totalsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='ledger_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='Ledger Id'),
        ),
    ]
